# ==============================
# Makefile for LED Strip project
# ==============================

#Targets
all: build run

build:
	gcc -o main ./src/main.c ./src/led_driver.c

run:
	./main

clean:
	rm -f ./main